/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Estudiantes
 */
public class VistaTablero extends javax.swing.JFrame {

    private Modelo modelo;
    private Controlador controlador;

    public VistaTablero(Modelo m) {
        modelo = m;
        initComponents();
        capturarEventos();
    }

    public Modelo getModelo() {
        return modelo;
    }

    public Controlador getControl() {
        if (controlador == null) {
            controlador = new Controlador(this);
        }
        return controlador;
    }
    
    
    
    public void capturarEventos() {
        c00.addActionListener(getControl());
        c01.addActionListener(getControl());
        c02.addActionListener(getControl());
        c03.addActionListener(getControl());
        c04.addActionListener(getControl());
        c05.addActionListener(getControl());
        c06.addActionListener(getControl());
        c07.addActionListener(getControl());

        c10.addActionListener(getControl());
        c11.addActionListener(getControl());
        c12.addActionListener(getControl());
        c13.addActionListener(getControl());
        c14.addActionListener(getControl());
        c15.addActionListener(getControl());
        c16.addActionListener(getControl());
        c17.addActionListener(getControl());

        c20.addActionListener(getControl());
        c21.addActionListener(getControl());
        c22.addActionListener(getControl());
        c23.addActionListener(getControl());
        c24.addActionListener(getControl());
        c25.addActionListener(getControl());
        c26.addActionListener(getControl());
        c27.addActionListener(getControl());

        c30.addActionListener(getControl());
        c31.addActionListener(getControl());
        c32.addActionListener(getControl());
        c33.addActionListener(getControl());
        c34.addActionListener(getControl());
        c35.addActionListener(getControl());
        c36.addActionListener(getControl());
        c37.addActionListener(getControl());

        c40.addActionListener(getControl());
        c41.addActionListener(getControl());
        c42.addActionListener(getControl());
        c43.addActionListener(getControl());
        c44.addActionListener(getControl());
        c45.addActionListener(getControl());
        c46.addActionListener(getControl());
        c47.addActionListener(getControl());

        c50.addActionListener(getControl());
        c51.addActionListener(getControl());
        c52.addActionListener(getControl());
        c53.addActionListener(getControl());
        c54.addActionListener(getControl());
        c55.addActionListener(getControl());
        c56.addActionListener(getControl());
        c57.addActionListener(getControl());

        c60.addActionListener(getControl());
        c61.addActionListener(getControl());
        c62.addActionListener(getControl());
        c63.addActionListener(getControl());
        c64.addActionListener(getControl());
        c65.addActionListener(getControl());
        c66.addActionListener(getControl());
        c67.addActionListener(getControl());

        c70.addActionListener(getControl());
        c71.addActionListener(getControl());
        c72.addActionListener(getControl());
        c73.addActionListener(getControl());
        c74.addActionListener(getControl());
        c75.addActionListener(getControl());
        c76.addActionListener(getControl());
        c77.addActionListener(getControl());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        c00 = new javax.swing.JButton();
        c01 = new javax.swing.JButton();
        c02 = new javax.swing.JButton();
        c03 = new javax.swing.JButton();
        c04 = new javax.swing.JButton();
        c05 = new javax.swing.JButton();
        c06 = new javax.swing.JButton();
        c07 = new javax.swing.JButton();
        c10 = new javax.swing.JButton();
        c11 = new javax.swing.JButton();
        c12 = new javax.swing.JButton();
        c13 = new javax.swing.JButton();
        c14 = new javax.swing.JButton();
        c15 = new javax.swing.JButton();
        c16 = new javax.swing.JButton();
        c17 = new javax.swing.JButton();
        c20 = new javax.swing.JButton();
        c21 = new javax.swing.JButton();
        c22 = new javax.swing.JButton();
        c23 = new javax.swing.JButton();
        c24 = new javax.swing.JButton();
        c25 = new javax.swing.JButton();
        c26 = new javax.swing.JButton();
        c27 = new javax.swing.JButton();
        c30 = new javax.swing.JButton();
        c31 = new javax.swing.JButton();
        c32 = new javax.swing.JButton();
        c33 = new javax.swing.JButton();
        c34 = new javax.swing.JButton();
        c35 = new javax.swing.JButton();
        c36 = new javax.swing.JButton();
        c37 = new javax.swing.JButton();
        c40 = new javax.swing.JButton();
        c41 = new javax.swing.JButton();
        c42 = new javax.swing.JButton();
        c43 = new javax.swing.JButton();
        c44 = new javax.swing.JButton();
        c45 = new javax.swing.JButton();
        c46 = new javax.swing.JButton();
        c47 = new javax.swing.JButton();
        c50 = new javax.swing.JButton();
        c51 = new javax.swing.JButton();
        c52 = new javax.swing.JButton();
        c53 = new javax.swing.JButton();
        c54 = new javax.swing.JButton();
        c55 = new javax.swing.JButton();
        c56 = new javax.swing.JButton();
        c57 = new javax.swing.JButton();
        c60 = new javax.swing.JButton();
        c61 = new javax.swing.JButton();
        c62 = new javax.swing.JButton();
        c63 = new javax.swing.JButton();
        c64 = new javax.swing.JButton();
        c65 = new javax.swing.JButton();
        c66 = new javax.swing.JButton();
        c67 = new javax.swing.JButton();
        c70 = new javax.swing.JButton();
        c71 = new javax.swing.JButton();
        c72 = new javax.swing.JButton();
        c73 = new javax.swing.JButton();
        c74 = new javax.swing.JButton();
        c75 = new javax.swing.JButton();
        c76 = new javax.swing.JButton();
        c77 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(12, 12, 12, 12, new java.awt.Color(101, 98, 98)));
        jPanel1.setForeground(new java.awt.Color(101, 98, 98));
        jPanel1.setToolTipText("");

        c00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/torren.png"))); // NOI18N
        c00.setToolTipText("");
        c00.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c01.setBackground(new java.awt.Color(101, 98, 98));
        c01.setForeground(new java.awt.Color(25, 25, 25));
        c01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caballon.png"))); // NOI18N
        c01.setToolTipText("");
        c01.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alfiln.png"))); // NOI18N
        c02.setToolTipText("");
        c02.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c03.setBackground(new java.awt.Color(101, 98, 98));
        c03.setForeground(new java.awt.Color(25, 25, 25));
        c03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reinan.png"))); // NOI18N
        c03.setToolTipText("");
        c03.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reyn.png"))); // NOI18N
        c04.setToolTipText("");
        c04.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c05.setBackground(new java.awt.Color(101, 98, 98));
        c05.setForeground(new java.awt.Color(25, 25, 25));
        c05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alfiln.png"))); // NOI18N
        c05.setToolTipText("");
        c05.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caballon.png"))); // NOI18N
        c06.setToolTipText("");
        c06.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c07.setBackground(new java.awt.Color(101, 98, 98));
        c07.setForeground(new java.awt.Color(25, 25, 25));
        c07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/torren.png"))); // NOI18N
        c07.setToolTipText("");
        c07.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c10.setBackground(new java.awt.Color(101, 98, 98));
        c10.setForeground(new java.awt.Color(25, 25, 25));
        c10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonn.png"))); // NOI18N
        c10.setToolTipText("");
        c10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonn.png"))); // NOI18N
        c11.setToolTipText("");
        c11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c12.setBackground(new java.awt.Color(101, 98, 98));
        c12.setForeground(new java.awt.Color(25, 25, 25));
        c12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonn.png"))); // NOI18N
        c12.setToolTipText("");
        c12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonn.png"))); // NOI18N
        c13.setToolTipText("");
        c13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c14.setBackground(new java.awt.Color(101, 98, 98));
        c14.setForeground(new java.awt.Color(25, 25, 25));
        c14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonn.png"))); // NOI18N
        c14.setToolTipText("");
        c14.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonn.png"))); // NOI18N
        c15.setToolTipText("");
        c15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c16.setBackground(new java.awt.Color(101, 98, 98));
        c16.setForeground(new java.awt.Color(25, 25, 25));
        c16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonn.png"))); // NOI18N
        c16.setToolTipText("");
        c16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonn.png"))); // NOI18N
        c17.setToolTipText("");
        c17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c20.setToolTipText("");
        c20.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c21.setBackground(new java.awt.Color(101, 98, 98));
        c21.setToolTipText("");
        c21.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c22.setToolTipText("");
        c22.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c23.setBackground(new java.awt.Color(101, 98, 98));
        c23.setToolTipText("");
        c23.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c24.setToolTipText("");
        c24.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c25.setBackground(new java.awt.Color(101, 98, 98));
        c25.setToolTipText("");
        c25.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c26.setToolTipText("");
        c26.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c27.setBackground(new java.awt.Color(101, 98, 98));
        c27.setToolTipText("");
        c27.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c30.setBackground(new java.awt.Color(101, 98, 98));
        c30.setToolTipText("");
        c30.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c31.setToolTipText("");
        c31.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c32.setBackground(new java.awt.Color(101, 98, 98));
        c32.setToolTipText("");
        c32.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c33.setToolTipText("");
        c33.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c34.setBackground(new java.awt.Color(101, 98, 98));
        c34.setToolTipText("");
        c34.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c35.setToolTipText("");
        c35.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c36.setBackground(new java.awt.Color(101, 98, 98));
        c36.setToolTipText("");
        c36.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c37.setToolTipText("");
        c37.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c40.setToolTipText("");
        c40.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c41.setBackground(new java.awt.Color(101, 98, 98));
        c41.setToolTipText("");
        c41.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c42.setToolTipText("");
        c42.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c43.setBackground(new java.awt.Color(101, 98, 98));
        c43.setToolTipText("");
        c43.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c44.setToolTipText("");
        c44.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c45.setBackground(new java.awt.Color(101, 98, 98));
        c45.setToolTipText("");
        c45.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c46.setToolTipText("");
        c46.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c47.setBackground(new java.awt.Color(101, 98, 98));
        c47.setToolTipText("");
        c47.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c50.setBackground(new java.awt.Color(101, 98, 98));
        c50.setToolTipText("");
        c50.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c51.setToolTipText("");
        c51.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c52.setBackground(new java.awt.Color(101, 98, 98));
        c52.setToolTipText("");
        c52.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c53.setToolTipText("");
        c53.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c54.setBackground(new java.awt.Color(101, 98, 98));
        c54.setToolTipText("");
        c54.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c55.setToolTipText("");
        c55.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c56.setBackground(new java.awt.Color(101, 98, 98));
        c56.setToolTipText("");
        c56.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c57.setBackground(new java.awt.Color(245, 245, 220));
        c57.setToolTipText("");
        c57.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c60.setForeground(new java.awt.Color(25, 25, 25));
        c60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonb.png"))); // NOI18N
        c60.setToolTipText("");
        c60.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c61.setBackground(new java.awt.Color(101, 98, 98));
        c61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonb.png"))); // NOI18N
        c61.setToolTipText("");
        c61.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c62.setForeground(new java.awt.Color(25, 25, 25));
        c62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonb.png"))); // NOI18N
        c62.setToolTipText("");
        c62.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c63.setBackground(new java.awt.Color(101, 98, 98));
        c63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonb.png"))); // NOI18N
        c63.setToolTipText("");
        c63.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c64.setForeground(new java.awt.Color(25, 25, 25));
        c64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonb.png"))); // NOI18N
        c64.setToolTipText("");
        c64.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c65.setBackground(new java.awt.Color(101, 98, 98));
        c65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonb.png"))); // NOI18N
        c65.setToolTipText("");
        c65.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c66.setForeground(new java.awt.Color(25, 25, 25));
        c66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonb.png"))); // NOI18N
        c66.setToolTipText("");
        c66.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c67.setBackground(new java.awt.Color(101, 98, 98));
        c67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonb.png"))); // NOI18N
        c67.setToolTipText("");
        c67.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c70.setBackground(new java.awt.Color(101, 98, 98));
        c70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/torreb.png"))); // NOI18N
        c70.setToolTipText("");
        c70.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c71.setForeground(new java.awt.Color(25, 25, 25));
        c71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caballob.png"))); // NOI18N
        c71.setToolTipText("");
        c71.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c72.setBackground(new java.awt.Color(101, 98, 98));
        c72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alfilb.png"))); // NOI18N
        c72.setToolTipText("");
        c72.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c73.setForeground(new java.awt.Color(25, 25, 25));
        c73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reinab.png"))); // NOI18N
        c73.setToolTipText("");
        c73.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c74.setBackground(new java.awt.Color(101, 98, 98));
        c74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reyb.png"))); // NOI18N
        c74.setToolTipText("");
        c74.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c75.setForeground(new java.awt.Color(25, 25, 25));
        c75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alfilb.png"))); // NOI18N
        c75.setToolTipText("");
        c75.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c76.setBackground(new java.awt.Color(101, 98, 98));
        c76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caballob.png"))); // NOI18N
        c76.setToolTipText("");
        c76.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c77.setForeground(new java.awt.Color(25, 25, 25));
        c77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/torreb.png"))); // NOI18N
        c77.setToolTipText("");
        c77.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(c00, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c01, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c02, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c03, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c04, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c05, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c06, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c07, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c16, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c17, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(c20, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c21, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c22, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c23, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c24, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c25, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c26, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c27, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(c30, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c31, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c32, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c33, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c34, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c35, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c36, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c37, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(c40, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c41, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c42, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c43, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c44, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c45, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c46, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c47, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(c50, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c51, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c52, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c53, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c54, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c55, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c56, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c57, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(c60, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c61, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c62, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c63, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c64, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c65, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c66, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c67, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(c70, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c71, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c72, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c73, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c74, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c75, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c76, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(c77, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(c00, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c01, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c02, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c03, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c04, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c05, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c06, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c07, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c16, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c17, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(c20, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c21, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c22, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c23, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c24, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c25, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c26, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c27, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(c30, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c31, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c32, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c33, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c34, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c35, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c36, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c37, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(c40, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c41, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c42, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c43, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c44, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c45, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c46, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c47, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(c50, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c51, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c52, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c53, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c54, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c55, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c56, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c57, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(c60, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c61, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c62, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c63, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c64, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c65, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c66, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c67, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(c70, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c71, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c72, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c73, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c74, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c75, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c76, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c77, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jMenu1.setText("Menu");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton c00;
    public static javax.swing.JButton c01;
    public static javax.swing.JButton c02;
    public static javax.swing.JButton c03;
    public static javax.swing.JButton c04;
    public static javax.swing.JButton c05;
    public static javax.swing.JButton c06;
    public static javax.swing.JButton c07;
    public static javax.swing.JButton c10;
    public static javax.swing.JButton c11;
    public static javax.swing.JButton c12;
    public static javax.swing.JButton c13;
    public static javax.swing.JButton c14;
    public static javax.swing.JButton c15;
    public static javax.swing.JButton c16;
    public static javax.swing.JButton c17;
    public static javax.swing.JButton c20;
    public static javax.swing.JButton c21;
    public static javax.swing.JButton c22;
    public static javax.swing.JButton c23;
    public static javax.swing.JButton c24;
    public static javax.swing.JButton c25;
    public static javax.swing.JButton c26;
    public static javax.swing.JButton c27;
    public static javax.swing.JButton c30;
    public static javax.swing.JButton c31;
    public static javax.swing.JButton c32;
    public static javax.swing.JButton c33;
    public static javax.swing.JButton c34;
    public static javax.swing.JButton c35;
    public static javax.swing.JButton c36;
    public static javax.swing.JButton c37;
    public static javax.swing.JButton c40;
    public static javax.swing.JButton c41;
    public static javax.swing.JButton c42;
    public static javax.swing.JButton c43;
    public static javax.swing.JButton c44;
    public static javax.swing.JButton c45;
    public static javax.swing.JButton c46;
    public static javax.swing.JButton c47;
    public static javax.swing.JButton c50;
    public static javax.swing.JButton c51;
    public static javax.swing.JButton c52;
    public static javax.swing.JButton c53;
    public static javax.swing.JButton c54;
    public static javax.swing.JButton c55;
    public static javax.swing.JButton c56;
    public static javax.swing.JButton c57;
    public static javax.swing.JButton c60;
    public static javax.swing.JButton c61;
    public static javax.swing.JButton c62;
    public static javax.swing.JButton c63;
    public static javax.swing.JButton c64;
    public static javax.swing.JButton c65;
    public static javax.swing.JButton c66;
    public static javax.swing.JButton c67;
    public static javax.swing.JButton c70;
    public static javax.swing.JButton c71;
    public static javax.swing.JButton c72;
    public static javax.swing.JButton c73;
    public static javax.swing.JButton c74;
    public static javax.swing.JButton c75;
    public static javax.swing.JButton c76;
    public static javax.swing.JButton c77;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


}
